version: "3" # docker-compose version
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine 
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    - 5672:5672 # your computers port : containers port # services will communicate through this port
    - 15672:15672 # admin panel
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.config:/etc/rabbitmq/conf.d/10-defaults.conf
    networks:
      - poc

networks:
  poc:
    driver: bridge 
    