default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'db' %>
  username: postgres
  password: password
  pool: <%= ENV.fetch("DB_POOL_THREADS") { 5 } %>
development:
  <<: *default
  database: pong_development
test:
  <<: *default
  database: pong_test